#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
import syslog
import argparse
from netcop.despachante import Despachante, models
 
# Manejo de argumentos
# ---------------------------------------------------------------------------
parser = argparse.ArgumentParser()
parser.add_argument("-t", "--temporizado",
                    help="Ejecuta el script en modo temporizado. Si no es "
                         "necesario un despacho nuevo, no hace nada.",
                    action="store_true")
args = parser.parse_args()

try:
    syslog.openlog('despachante')
    models.db.connect()
    despachante = Despachante() 
    if not args.temporizado or despachante.despacho_necesario():
        syslog.syslog(syslog.LOG_INFO, "Despachando politicas")
        despachante.despachar()
    else:
        print("No hay necesidad de despacho.")
except Exception as e:
    syslog.syslog(syslog.LOG_CRIT, "Error fatal: %s" % str(e))
    print >> sys.stderr, str(e)
    raise
finally:
    syslog.closelog()
    if not models.db.is_closed():
        models.db.close()
