#!/usr/bin/env python
# -*- coding: utf-8 -*-
import sys
import syslog
import argparse
from netcop.despachante import Despachante, models

# Manejo de argumentos
# ---------------------------------------------------------------------------
parser = argparse.ArgumentParser()
parser.add_argument("-t", "--temporizado",
                    help="Ejecuta el script en modo temporizado. Si no es "
                         "necesario un despacho nuevo, no hace nada.",
                    action="store_true")
args = parser.parse_args()

try:
    syslog.openlog('despachante')
    syslog.syslog(syslog.LOG_DEBUG, "[*] Conectando base de datos")
    models.db.connect()
    despachante = Despachante()
    programado = args.temporizado
    necesario = despachante.despacho_necesario()
    syslog.syslog(syslog.LOG_DEBUG, "[*] Despacho programado: %s" % programado)
    syslog.syslog(syslog.LOG_DEBUG, "[*] Despacho necesario: %s" % necesario)
    if not programado or necesario:
        syslog.syslog(syslog.LOG_INFO, "Despachando politicas")
        despachante.despachar()
        syslog.syslog(syslog.LOG_INFO, "El despacho fue exitoso")
    else:
        syslog.syslog(syslog.LOG_INFO, "No hay necesidad de despacho")
        print("No hay necesidad de despacho.")
except Exception as e:
    syslog.syslog(syslog.LOG_CRIT, "Error fatal: %s" % str(e))
    print >> sys.stderr, str(e)
    raise
finally:
    syslog.closelog()
    if not models.db.is_closed():
        syslog.syslog(syslog.LOG_DEBUG, "[*] Cerrando base de datos")
        models.db.close()
